### ISSUE TITLE
OpenBSD: Runtime port has crashed

### ISSUE THREAD

**Issue by bonds** [passff/passff#217]
I'm having trouble getting passff 1.0 to work on Firefox 52.0.2 on OpenBSD 6.1-stable amd64. When I click on the passff button within Firefox, I see the error:

````
Sorry, an unexpected error occured. Make sure your preferences are correctly set and that the native host app is installed.
````
Opening the browser console I see:

````
[PassFF] Preferences initialised Object { passwordInputNames: Array[3], loginInputNames: Array[8], loginFieldNames: Array[4], passwordFieldNames: Array[3], urlFieldNames: Array[2], command: "/home/scott/src/password-store/src/…", commandArgs: Array[1], shell: "/bin/bash", shellArgs: Array[1], home: "", 10 more… }  main.js:16:7
cannot read contents of null pointer ctypes.char.ptr.ptr(ctypes.UInt64("0x0"))  NativeMessaging.jsm:216
	this.NativeApp</this.startupPromise< resource://gre/modules/NativeMessaging.jsm:216:9
[PassFF] Error detecting GPG Agent: Error: Attempt to postMessage on disconnected port  main.js:16:7
	logPrototype moz-extension://685d47d1-eae6-431b-b4f7-8d1bccc56606/modules/main.js:16:7
	PassFF.Preferences.init/PassFF.Preferences</< moz-extension://685d47d1-eae6-431b-b4f7-8d1bccc56606/modules/preferences.js:96:15
cannot read contents of null pointer ctypes.char.ptr.ptr(ctypes.UInt64("0x0"))  NativeMessaging.jsm:216
	this.NativeApp</this.startupPromise< resource://gre/modules/NativeMessaging.jsm:216:9
[PassFF] Error initializing preferences: Error: Attempt to postMessage on disconnected port  main.js:16:7
	logPrototype moz-extension://685d47d1-eae6-431b-b4f7-8d1bccc56606/modules/main.js:16:7
	PassFF.init/< moz-extension://685d47d1-eae6-431b-b4f7-8d1bccc56606/modules/main.js:125:9
````
and
````
[PassFF] Initializing Menu  main.js:16:7
[PassFF] Runtime port has crashed: Error: Could not establish connection. Receiving end does not exist.  main.js:16:7
	logPrototype moz-extension://685d47d1-eae6-431b-b4f7-8d1bccc56606/modules/main.js:16:7
	PassFF.bg_exec/< moz-extension://685d47d1-eae6-431b-b4f7-8d1bccc56606/modules/main.js:157:7
[PassFF] Error restoring menu : TypeError: menu_state is undefined
Stack trace:
PassFF.Menu.init/<@moz-extension://685d47d1-eae6-431b-b4f7-8d1bccc56606/modules/menu.js:24:1
  main.js:16:7
	logPrototype moz-extension://685d47d1-eae6-431b-b4f7-8d1bccc56606/modules/main.js:16:7
	logAndDisplayError/< moz-extension://685d47d1-eae6-431b-b4f7-8d1bccc56606/modules/menu.js:9:5
````

**Comment by bonds** [comment]
I noticed the ````ctypes.char.ptr.ptr(ctypes.UInt64("0x0"))```` error on browserpass too: https://github.com/dannyvankooten/browserpass/issues/113

**Comment by phryneas** [comment]
Just to make sure: You have installed the host application?

**Comment by bonds** [comment]
Yes, the host application is installed. To sanity check that, I renamed /home/scott/.mozilla/native-messaging-hosts/passff.json to /home/scott/.mozilla/native-messaging-hosts/passff.json.old and relaunched Firefox, yielding this new error message:

````
[PassFF] Preferences initialised Object { passwordInputNames: Array[3], loginInputNames: Array[8], loginFieldNames: Array[4], passwordFieldNames: Array[3], urlFieldNames: Array[2], command: "/home/scott/src/password-store/src/…", commandArgs: Array[1], shell: "/bin/bash", shellArgs: Array[1], home: "", 10 more… }  main.js:16:7
This extension does not have permission to use native application passff (or the application is not installed)  NativeMessaging.jsm:216
	this.NativeApp</this.startupPromise< resource://gre/modules/NativeMessaging.jsm:216:9
[PassFF] Error detecting GPG Agent: Error: Attempt to postMessage on disconnected port  main.js:16:7
	logPrototype moz-extension://685d47d1-eae6-431b-b4f7-8d1bccc56606/modules/main.js:16:7
	PassFF.Preferences.init/PassFF.Preferences</< moz-extension://685d47d1-eae6-431b-b4f7-8d1bccc56606/modules/preferences.js:96:15
This extension does not have permission to use native application passff (or the application is not installed)  NativeMessaging.jsm:216
	this.NativeApp</this.startupPromise< resource://gre/modules/NativeMessaging.jsm:216:9
[PassFF] Error initializing preferences: Error: Attempt to postMessage on disconnected port  main.js:16:7
	logPrototype moz-extension://685d47d1-eae6-431b-b4f7-8d1bccc56606/modules/main.js:16:7
	PassFF.init/< moz-extension://685d47d1-eae6-431b-b4f7-8d1bccc56606/modules/main.js:125:9
````
The difference being, when the passff host application is NOT installed, the first error is
````
This extension does not have permission to use native application passff (or the application is not installed)  NativeMessaging.jsm:216
````
But when the passff host application IS installed, the first error is:
````
cannot read contents of null pointer ctypes.char.ptr.ptr(ctypes.UInt64("0x0"))  NativeMessaging.jsm:216
````

**Comment by mddvul22** [comment]
I'm experiencing this same issue with Firefox 52.3.0 on Debian 9.0.  So this isn't just an issue on OpenBSD.

**Comment by devurandom** [comment]
Same error message `Sorry, an unexpected error occured. Make sure your preferences are correctly set and that the native host app is installed.` with Firefox 55.0.2 on Gentoo Linux with Pass 1.7.1. There is no related output on the console that I started Firefox from. There is no output on the console that opens when right-clicking and selecting "Inspect Element (Q)". Which "browser console" are you referring to?

**Comment by bonds** [comment]
@devurandom I'm referring to 'the hamburger menu' -> Developer -> Browser Console. For me it's also mapped to Ctrl-Shift-J

**Comment by devurandom** [comment]
@bonds: Thanks!

After opening the PassFF menu:
```
22:20:59.099 [PassFF] Initializing Menu 1 main.js:16:7

22:19:52.163 [PassFF] Runtime port has crashed: Error: Could not establish connection. Receiving end does not exist. 1 main.js:16:7
	logPrototype moz-extension://5433584d-dc44-4d6d-993f-1b1ec94e6081/modules/main.js:16:7
	bg_exec/< moz-extension://5433584d-dc44-4d6d-993f-1b1ec94e6081/modules/main.js:157:7

22:19:52.167 [PassFF] Error restoring menu : TypeError: menu_state is undefined
Stack-Trace:
init/<@moz-extension://5433584d-dc44-4d6d-993f-1b1ec94e6081/modules/menu.js:24:1
 1 main.js:16:7
	logPrototype moz-extension://5433584d-dc44-4d6d-993f-1b1ec94e6081/modules/main.js:16:7
	logAndDisplayError/< moz-extension://5433584d-dc44-4d6d-993f-1b1ec94e6081/modules/menu.js:9:5
```

Clicking reload icon:
```
22:21:16.421 [PassFF] Refresh click { target: <button#passff-refresh-menuitem.icon.reload>, buttons: 0, clientX: 366, clientY: 230, layerX: 20, layerY: 22 } 1 main.js:16:7

22:21:16.426 TypeError: el.parentNode is not a function 1 menu.js:206:7
	onRefresh/< moz-extension://5433584d-dc44-4d6d-993f-1b1ec94e6081/modules/menu.js:206:7
	forEach self-hosted:267:13
	onRefresh moz-extension://5433584d-dc44-4d6d-993f-1b1ec94e6081/modules/menu.js:205:5
```

Clicking "Display root":
```
22:21:54.942 [PassFF] Root button command click { target: <button#passff-root-button>, buttons: 0, clientX: 70, clientY: 231, layerX: 70, layerY: 23 } 1 main.js:16:7

22:21:54.955 [PassFF] Runtime port has crashed: Error: Could not establish connection. Receiving end does not exist. 1 main.js:16:7
	logPrototype moz-extension://5433584d-dc44-4d6d-993f-1b1ec94e6081/modules/main.js:16:7
	bg_exec/< moz-extension://5433584d-dc44-4d6d-993f-1b1ec94e6081/modules/main.js:157:7

22:21:54.957 [PassFF] Create children menu list undefined undefined 1 main.js:16:7

22:21:54.958 [PassFF] Error getting root items on button press : TypeError: items is undefined
Stack-Trace:
createItemsMenuList@moz-extension://5433584d-dc44-4d6d-993f-1b1ec94e6081/modules/menu.js:342:5
onRootButtonCommand/<@moz-extension://5433584d-dc44-4d6d-993f-1b1ec94e6081/modules/menu.js:193:7
 1 main.js:16:7
	logPrototype moz-extension://5433584d-dc44-4d6d-993f-1b1ec94e6081/modules/main.js:16:7
	logAndDisplayError/< moz-extension://5433584d-dc44-4d6d-993f-1b1ec94e6081/modules/menu.js:9:5
```

Clicking "Display context":
```
22:22:56.547 [PassFF] Context button command click { target: <button#passff-context-button>, buttons: 0, clientX: 192, clientY: 234, layerX: 48, layerY: 26 } 1 main.js:16:7

22:22:56.553 [PassFF] Create contextual menu 1 main.js:16:7

22:22:56.564 [PassFF] Runtime port has crashed: Error: Could not establish connection. Receiving end does not exist. 1 main.js:16:7
	logPrototype moz-extension://5433584d-dc44-4d6d-993f-1b1ec94e6081/modules/main.js:16:7
	bg_exec/< moz-extension://5433584d-dc44-4d6d-993f-1b1ec94e6081/modules/main.js:157:7

22:22:56.567 [PassFF] Create children menu list undefined undefined 1 main.js:16:7

22:22:56.568 [PassFF] Error getting matching items on create contextual menu : TypeError: items is undefined
Stack-Trace:
createItemsMenuList@moz-extension://5433584d-dc44-4d6d-993f-1b1ec94e6081/modules/menu.js:342:5
createContextualMenu/<@moz-extension://5433584d-dc44-4d6d-993f-1b1ec94e6081/modules/menu.js:326:9
 1 main.js:16:7
	logPrototype moz-extension://5433584d-dc44-4d6d-993f-1b1ec94e6081/modules/main.js:16:7
	logAndDisplayError/< moz-extension://5433584d-dc44-4d6d-993f-1b1ec94e6081/modules/menu.js:9:5
```

Clicking gearwheel icon logs nothing at all, and still has no visible effect, either.

Clicking the plus icon (only those lines mentioning `moz-extension://5433584d-dc44-4d6d-993f-1b1ec94e6081`):
```
Cannot send function call result: other side closed connection (call data: ({path:"windows.create", args:[{url:"moz-extension://5433584d-dc44-4d6d-993f-1b1ec94e6081/content/newPasswordWindow.html", tabId:null, left:null, top:null, width:450, height:330, incognito:null, type:"popup", state:null, allowScriptsToClose:null}]}))
```

**Comment by schulmar** [comment]
I saw a similar if not the same issue on Arch Linux with FF 55.0.3
I tried to reinstall the extension but now I only see 0.1.30 in the addons search whereas I am certain that I had 1.xx installed before.

**Comment by schulmar** [comment]
Okay, shame on me. I did not use the install script and had an invalid setup of the host app.
The manifest file `passff.json` was not correctly patched to contain the path to `passff.py` and the execute right on `passff.py` was not set. After fixing that it seems to work.

**Comment by mddvul22** [comment]
I'm running 1.01linux and still have the error.  I have also created a brand new firefox profile and installed the extension and still receive the error.

**Comment by mddvul22** [comment]
OK, double-shame on me.  I've read through this bug report and have read mention of the host app and still had not ever installed that.  I take it that the host app is something new?  I've been using passff for a couple of years and have never had to do that.  Anyway, again, double-shame on me.  I've now installed the host app and passff is again working for me.  Sorry for creating noise in this bug report.

**Comment by devurandom** [comment]
> Okay, shame on me. I did not use the install script and had an invalid setup of the host app.
The manifest file passff.json was not correctly patched to contain the path to passff.py and the execute right on passff.py was not set. After fixing that it seems to work.

Could you please provide more information on these files? I cannot find them on my computer -- they do not appear to come with the passff extension. I do have `/usr/bin/pass` installed, though that seems not to be what you are referring to?

**Comment by tuxor1337** [comment]
See installation instructions for information about the host app: https://github.com/passff/passff/blob/master/docs/INSTALLATION.md#installing-the-host-application

**Comment by tuxor1337** [comment]
Is this still an issue on Debian or OpenBSD and the latest version of PassFF? If so, can somebody please check whether it's related to the path in `passff.json` not being set or the execute rights on `passff.py` being wrong?

**Comment by bonds** [comment]
I'm running OpenBSD amd64 6.2-stable, Firefox 58.0.2 64-bit, PassFF 1.1. I manually installed the host app since the install script had trouble (see https://github.com/passff/passff-host/issues/5). I edited the passff.json to point to the passff.py file and I edited the passff.py file to refer to my gopass executable.

passff.py is executable:

````
~/.m/native-messaging-hosts ❯❯❯ pwd                                         Tue 2018-03-27 08:41:01 -0700
/home/scott/.mozilla/native-messaging-hosts
~/.m/native-messaging-hosts ❯❯❯ ls -alh                                     Tue 2018-03-27 08:41:13 -0700
total 24
drwxr-xr-x  2 scott  scott   512B Jan 23 12:59 .
drwxr-xr-x  5 scott  scott   512B Jan 14 15:14 ..
-rw-r--r--  1 scott  scott   253B Nov 16 09:01 com.dannyvankooten.browserpass.json
-rw-r--r--  1 scott  scott   218B Mar 27 08:34 passff.json
-rwxr-xr-x  1 scott  scott   3.2K Mar 27 08:35 passff.py
````
Running it on the console shows this:
````
~/.m/native-messaging-hosts ❯❯❯ ./passff.py                                 Tue 2018-03-27 08:41:15 -0700
hello there
Traceback (most recent call last):
  File "./passff.py", line 52, in <module>
    receivedMessage = getMessage()
  File "./passff.py", line 35, in getMessage
    message = sys.stdin.buffer.read(messageLength).decode("utf-8")
MemoryError
````
When I attempt to use the passff addon in Firefox by clicking on the passff icon, I can see the search UI and the bottom menu (Display Root, etc) but clicking on Display Root doesn't do anything, and trying to search doesn't do anything.

In the Browser Console I see this:
````
cannot read contents of null pointer ctypes.char.ptr.ptr(ctypes.UInt64("0x0"))  subprocess_unix.jsm:121
	getEnvironment resource://gre/modules/subprocess/subprocess_unix.jsm:121:30
	InterpretGeneratorResume self-hosted:1231:8
	next self-hosted:1186:9
	getEnvironment resource://gre/modules/Subprocess.jsm:146:5
	call resource://gre/modules/Subprocess.jsm:113:21
	this.NativeApp</this.startupPromise< resource://gre/modules/NativeMessaging.jsm:91:16
[PassFF] Error executing pass script Error: Attempt to postMessage on disconnected port  util.js:35:7
	logPrototype moz-extension://8bcc922f-52be-49b8-ba8b-aef74c1cb525/modules/util.js:35:7
	PassFF.Pass.executePass</< moz-extension://8bcc922f-52be-49b8-ba8b-aef74c1cb525/modules/pass.js:216:13
TypeError: items is undefined[Learn More]  pass.js:159:11
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object.[Learn More]
````

**Comment by bonds** [comment]
@tuxor1337 in short, yes, passff is still broken on OpenBSD, passff.py is executable, and passff.json points to passff.py (once I manually installed and edited passff.json and passff.py):

````
~/.m/native-messaging-hosts  [1] ❯❯❯ cat passff.json                        Tue 2018-03-27 08:44:58 -0700
{
  "name": "passff",
  "description": "Host for communicating with zx2c4 pass",
  "path": "/home/scott/.mozilla/native-messaging-hosts/passff.py",
  "type": "stdio",
  "allowed_extensions": [ "passff@invicem.pro" ]
}
````

**Comment by tuxor1337** [comment]
Why do you use the outdated version 1.1 of PassFF?

**Comment by bonds** [comment]
Sorry,  I thought the addon would automatically update to the latest version on its own. I'll download v1.2, try it, and report back.

**Comment by 5bentz** [comment]
You get a strange `MemoryError` at the end of your execution, while I don't get it:

```
5bentz@host % head ./passff.py 
#!/usr/bin/env python3

"""
    Host application of the browser extension PassFF
    that wraps around the zx2c4 pass script.
"""

import os, sys, json, struct, subprocess

VERSION = "1.0.1"
5bentz@host % ./passff.py 
passff.py is waiting for some input
hello there =)
I'm trapped!
Let's Ctrl+C
^CTraceback (most recent call last):
  File "./passff.py", line 52, in <module>
    receivedMessage = getMessage()
  File "./passff.py", line 35, in getMessage
    message = sys.stdin.buffer.read(messageLength).decode("utf-8")
KeyboardInterrupt
```

I also see you get the same error message with https://github.com/dannyvankooten/browserpass/issues/113 :/

**Comment by bonds** [comment]
Yes, I don't know what to make of the memory error. In other news, I upgraded to v1.2 and now I see this error message when I click on the passff button within Firefox:

````


Connection to the host app failed or returned an unexpected result!

Make sure you have the latest version of the PassFF host app installed by following the installation instructions on GitHub.
````

**Comment by tuxor1337** [comment]
Which version of the host app do you have installed now? We need the value of the "VERSION" variable in you `passff.py`.

**Comment by tuxor1337** [comment]
Oh and by the way: You cannot simply call `passff.py` from the command line in the way you are trying to do it. It expects standard input to start with four bytes for the message length.

**Comment by bonds** [comment]
I manually installed the passff.py from passff-host @master: https://github.com/passff/passff-host/commit/1feab77c59bab91451242dba0fa3f1e6cf95e8f9. Here's the whole thing:

````
#!/usr/bin/env python3

"""
    Host application of the browser extension PassFF
    that wraps around the zx2c4 pass script.
"""

import os, sys, json, struct, subprocess

VERSION = "_VERSIONHOLDER_"

################################################################################
######################## Begin preferences section #############################
################################################################################
# Default command for MacOS:
#COMMAND = "/usr/local/bin/pass"
COMMAND      = "/home/scott/.gocode/bin/gopass"
COMMAND_ARGS = []
COMMAND_ENV  = {
    "TREE_CHARSET": "ISO-8859-1",
    # Default PATH for MacOS:
    #"PATH": "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
}
CHARSET      = "UTF-8"
################################################################################
######################### End preferences section ##############################
################################################################################

def getMessage():
    """ Read a message from stdin and decode it. """
    rawLength = sys.stdin.buffer.read(4)
    if len(rawLength) == 0:
        sys.exit(0)
    messageLength = struct.unpack('@I', rawLength)[0]
    message = sys.stdin.buffer.read(messageLength).decode("utf-8")
    return json.loads(message)

def encodeMessage(messageContent):
    """ Encode a message for transmission, given its content. """
    encodedContent = json.dumps(messageContent)
    encodedLength = struct.pack('@I', len(encodedContent))
    return {'length': encodedLength, 'content': encodedContent}

def sendMessage(encodedMessage):
    """ Send an encoded message to stdout. """
    sys.stdout.buffer.write(encodedMessage['length'])
    sys.stdout.write(encodedMessage['content'])
    sys.stdout.flush()

if __name__ == "__main__":
    # Read message from standard input
    receivedMessage = getMessage()
    opt_args = []
    pos_args = []
    std_input = None

    if len(receivedMessage) == 0:
        pass
    elif receivedMessage[0] == "insert":
        opt_args = ["insert", "-m"]
        pos_args = [receivedMessage[1]]
        std_input = receivedMessage[2]
    elif receivedMessage[0] == "generate":
        pos_args = [receivedMessage[1], receivedMessage[2]]
        opt_args = ["generate"]
        if "-n" in receivedMessage[3:]:
            opt_args.append("-n")
    else:
        key = receivedMessage[0]
        key = "/" + (key[1:] if key[0] == "/" else key)
        pos_args = [key]
    opt_args += COMMAND_ARGS

    # Set up (modified) command environment
    env = dict(os.environ)
    if "HOME" not in env:
        env["HOME"] = os.path.expanduser('~')
    for key, val in COMMAND_ENV.items():
        env[key] = val

    # Set up subprocess params
    cmd = [COMMAND] + opt_args + ['--'] + pos_args
    proc_params = {
        'input': bytes(std_input, CHARSET) if std_input else None,
        'stdout': subprocess.PIPE,
        'stderr': subprocess.PIPE,
        'env': env
    }

    # Run and communicate with pass script
    proc = subprocess.run(cmd, **proc_params)

    # Send response
    sendMessage(encodeMessage({
        "exitCode": proc.returncode,
        "stdout": proc.stdout.decode(CHARSET),
        "stderr": proc.stderr.decode(CHARSET),
        "version": VERSION
    }))
````
Running passff.py like you said seems to work, outputting a list of password names in JSON. Here's the output, minus the password names:
````
~/.m/native-messaging-hosts  [1] ❯❯❯ echo -e "\x00\x00\x00\x02{}" | ./passff.py |  tail -c +4
{"exitCode": 0, "stdout": "gopass\n\u251c\u2500\u2500
...
, "stderr": "", "version": "_VERSIONHOLDER_"}⏎ 
````

**Comment by tuxor1337** [comment]
Installing the host app like this is not officially supported. This is the official way to do it: https://github.com/passff/passff-host#latest-from-github If the `make` part fails for you, you have to wait for a fix or you do manually what `make` is supposed to do which basically means replacing the `_VERSIONHOLDER_` by a supported version string (like `testing`).

**Comment by bonds** [comment]
Ahah...I used ````make```` when I should have used ````gmake````:

````
~/t/p/src (master|✔) ❯❯❯ make                                               Tue 2018-03-27 16:13:49 -0700
make: don't know how to make ../bin/testing/%: (prerequisite of: ../bin/testing/install_host_app.bat)
Stop in /home/scott/tmp/passff-host/src
~/t/p/src (master|✔)  [2] ❯❯❯ gmake                                         Tue 2018-03-27 16:13:50 -0700
mkdir -p ../bin/testing
cp ./install_host_app.bat ../bin/testing/install_host_app.bat
sed -i "s/_VERSIONHOLDER_/testing/g" ../bin/testing/install_host_app.bat
cp ./install_host_app.sh ../bin/testing/install_host_app.sh
sed -i "s/_VERSIONHOLDER_/testing/g" ../bin/testing/install_host_app.sh
cp ./passff.py ../bin/testing/passff.py
sed -i "s/_VERSIONHOLDER_/testing/g" ../bin/testing/passff.py
cp ./passff.json ../bin/testing/passff.json
sed -i "s/_VERSIONHOLDER_/testing/g" ../bin/testing/passff.json
````
Ok, so now I was able to follow the manual installation instructions, and passff.py has 'testing' as the version.

**Comment by tuxor1337** [comment]
@bonds Does it work now?

**Comment by bonds** [comment]
@tuxor1337 no...the host installer works ok now, but the addon still does not. If I disable passff (the addon in Firefox), clear the Browser Console, then enable passff, here's what's output to the console:
````
cannot read contents of null pointer ctypes.char.ptr.ptr(ctypes.UInt64("0x0"))  subprocess_unix.jsm:121
[PassFF] Error executing pass script Error: Attempt to postMessage on disconnected port  util.js:36:9
[PassFF] loadItems failed!  util.js:36:9
[PassFF] Init auth module  util.js:36:9
[PassFF] Awaiting tab init... 16 about:addons  util.js:36:9
[PassFF] Tab init done 16 about:addons  util.js:36:9
[PassFF] Awaiting tab init... 16 about:addons  util.js:36:9
[PassFF] Tab init done 16 about:addons  util.js:36:9
````
When I click on the passff button I see the popup with:
````


Connection to the host app failed or returned an unexpected result!

Make sure you have the latest version of the PassFF host app installed by following the installation instructions on GitHub.
````
The 'cannot read contents of null pointer' message expands into this detail:
````
getEnvironment resource://gre/modules/subprocess/subprocess_unix.jsm:121:30
	InterpretGeneratorResume self-hosted:1231:8
	next self-hosted:1186:9
	getEnvironment resource://gre/modules/Subprocess.jsm:146:5
	call resource://gre/modules/Subprocess.jsm:113:21
	this.NativeApp</this.startupPromise< resource://gre/modules/NativeMessaging.jsm:91:16
````
The '[PassFF] Error executing pass script' expands into this detail:
````
logPrototype moz-extension://8bcc922f-52be-49b8-ba8b-aef74c1cb525/modules/util.js:36:9
	PassFF.Pass.executePass</< moz-extension://8bcc922f-52be-49b8-ba8b-aef74c1cb525/modules/pass.js:194:13
````

**Comment by tuxor1337** [comment]
I'm out, I have no idea, what's happening here.

**Comment by kode9** [comment]
Hello,

I'm having something similar on Firefox 59.0.2 (64-bit).

```
Connection to the host app failed or returned an unexpected result!

Make sure you have the latest version of the PassFF host app installed by following the installation instructions on GitHub.
```

I enabled debugging, disabled passff then enabled it again, and I have this in the debug console :

```
[PassFF] Message Pass.loadItems received in background  util.js:36:9
[PassFF] Error executing pass script Error: An unexpected error occurred  util.js:36:9
	logPrototype moz-extension://87812f35-03bc-4333-951a-027f5598c0ce/modules/util.js:36:9
	PassFF.Pass.executePass</< moz-extension://87812f35-03bc-4333-951a-027f5598c0ce/modules/pass.js:207:13
[PassFF] loadItems failed!  util.js:36:9
[PassFF] Init auth module  util.js:36:9
[PassFF] Awaiting tab init... 50 about:addons  util.js:36:9
[PassFF] Tab init done 50 about:addons  util.js:36:9
Strict-Transport-Security: The connection to the site is untrustworthy, so the specified header was ignored.[Learn More]  entry.cgi
[PassFF] Awaiting tab init... 50 about:addons  util.js:36:9
[PassFF] Tab init done 50 about:addons  util.js:36:9
```

I then have this everytime I click on the passff button :

```
[PassFF] Awaiting tab init... 50 about:addons  util.js:36:9
[PassFF] 0 matches for about:addons  util.js:36:9
[PassFF] Tab init done 50 about:addons  util.js:36:9
[PassFF] Message Pass.loadItems received in background  util.js:36:9
[PassFF] Message Menu.getLastState received in background  util.js:36:9
[PassFF] Create menu list Array [  ]  util.js:36:9
[PassFF] Create children menu list Array [  ] true  util.js:36:9
[PassFF] Awaiting tab init... 50 about:addons  util.js:36:9
[PassFF] Tab init done 50 about:addons  util.js:36:9
```

Anything I can do to debug this ?

**Comment by 5bentz** [comment]
@kode9 I understand this is similar, however it doesn't look the same for me.
So, could you create a new issue please? And verify that `pass` works (in the CLI!). Thanks!

**Comment by bonds** [comment]
@tuxor1337 thanks for giving it a shot! I'm suspicious of this part of the error:
````
cannot read contents of null pointer ctypes.char.ptr.ptr(ctypes.UInt64("0x0"))
````
I'd be happy to stand up an OpenBSD box with SSH access and VNC for you to login and poke around if you care to tinker with it. If that doesn't sound like fun to you or any other maintainers, would y'all be interested in a PR to add a note in the README pointing out it doesn't work on OpenBSD? Then I'll close this ticket so as to not pollute the issues list.

**Comment by tuxor1337** [comment]
Thanks for the offer! I lack the time to further look into this. Maybe somebody else? There are other BSD users, so we leave this open for reference.

**Comment by tuxor1337** [comment]
Closing due to inactivity.

Since this seems to be related to the host application, please open a new issue in the [passff-host repository](https://github.com/passff/passff-host/issues) in case you would like to continue the discussion.
