### ISSUE TITLE
MacOS: Connection to host app failed

### ISSUE THREAD

**Issue by mziegler8888** [passff/passff#324]
Just installed the latest version of the Firefox plugin and host application. Unfortunately i get an content security policy error in Firefox. Details cana be found below.

Any help is appreciated!

Thank you in advance anc Cheers.

Martin

### General information. Describe your environment

- Versions
  - Operating system: MAC OS 10.13.4
  - Browser:  Firefox 59.0.2
  - PassFF: 1.3
  - Host app: Current master branch

Status line output: `[19:50:09] ls -> (-1)`

- Your preferences
  - In PassFF: Defaults
  - In the host app `passff.py`: Defaults except path to passff.py
- Messages in the web console: 
```
[PassFF] 0 matches for https://www.google.de/search?safe=off&dcr=0&source=hp&ei=UPnMWr6OKc2y0gWQ_LP4Aw&q=passff+Connection+to+the+host+app+failed+or+returned+an+unexpected+result&oq=passff+Connection+to+the+host+app+failed+or+returned+an+unexpected+result&gs_l=psy-ab.3...7330.13384.0.14018.12.10.0.0.0.0.94.716.9.10.0....0...1c.2.64.psy-ab..2.7.530.0..0j0i131k1j0i10i30k1j0i30k1j0i19k1j0i10i30i19k1j0i30i19k1.62.LEf-YkKFgLQ
util.js:36:9
[PassFF] Input search depth 0
util.js:36:9
[PassFF] Start pref-auto-fill
util.js:36:9
[PassFF] Input search depth 0
util.js:36:9
CSI/tbsd_
cb=gapi.loaded_0:336:127
CSI/_tbnd
cb=gapi.loaded_0:336:127
[PassFF] Input search depth 0
util.js:36:9
[PassFF] Input search depth 1
util.js:36:9
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
[PassFF] Input search depth 0
util.js:36:9
```

---

### Actual behaviour
Error message: Connection to the host app failed or returned an unexpected result!

Make sure you have the latest version of the PassFF host app installed by following the installation instructions on GitHub.

**Comment by 5bentz** [comment]
Could you please follow this procedure?

#### Remove old installations
* Delete any file `passff.json` in the folders `native-messaging-hosts` and `NativeMessagingHosts`
  * For the complete paths of these folders for your OS and browser, see https://github.com/passff/passff-host/

#### Reinstall the host application
See https://github.com/passff/passff-host/

#### Check that the host application is correctly installed
* Make sure the file `passff.py` is executable
  * `ls -l /path/to/passff.py`
* Open `passff.json` and verify `path` is set to the absolute path of the host executable `passff.py`: for example `"path": "/path/to/passff.py"`

#### Test passff

### If nothing above has worked out your issue...

#### Check the output of the host app
* Run `echo -e "\x02\x00\x00\x00[]" | /path/to/passff.py | tail -c +4; echo`
  * The typical output for an empty store is:
    * `{"stderr": "", "version": "1.0.1", "exitCode": 0, "stdout": "Password Store\n"}`

### Preferences
By modifying the `preferences section` in `passff.py` you will be able to set
  - the path to the `pass` script,
  - additional command line arguments that are passed to `pass`,
  - the shell `stdout` charset,
  - additional environment variables.

**Comment by CCheCastaldo** [comment]
I am having a similar, if not identical issue. 

General information. Describe your environment

    Versions
        Operating system: MAC OS 10.13.4
        Browser: Firefox 59.0.2
        PassFF: 1.3
        Host app: Current master branch

Status line output: `[21:35:46] show -> gpg: decryption failed: No sec... (2)`

    Your preferences
        In PassFF: Defaults
        In the host app passff.py: Defaults except path to passff.py

Actual Behavior

I originally got `passff` to work but only intermittently. Sometimes it would connect to pass without a gpg error and I was able to goto, fill, etc. and sometimes I would get the gpg error and nothing would happen when trying to use `passff`. I saw this post and tried the suggestions from 5bentz and now it does not work at all. Right now, `passff` can see the files in pass. However, when I click on them and select an action, nothing happens (there is no output to the web console either). I tried/confirmed:

1) I deleted any file `passff.json` in the folder `NativeMessagingHosts` and reinstalled the latest version of the host application. This is the only location on OS X where the host application puts files according to the `passff` documentation.

2) I made sure `passff.py` is executable and I opened `passff.json` and verified the path is set to the absolute path of the host executable `passff.py`.

3) I confirmed in the `passff.py` script that the path to pass matches its location in `/usr/local/bin/pass`, right where homebrew put it.

4) I ran `echo -e "\x02\x00\x00\x00[]" | /path/to/passff.py | tail -c +4; echo` and the output was similar to the empty store output plus my actual files in pass.

5) I know pass works just fine as I use it all the time from the command line.

Any help would be greatly appreciated. Thanks.

Chris

**Comment by 5bentz** [comment]
@CCheCastaldo 
To be honest, your problem is not similar since you don't have the same error in the statusline. Moreover, your passff can list the files whereas OP's cannot.

> This is the only location on OS X where the host application puts files according to the passff documentation.

*Actually* the doc seems wrong since the installer of the native host app has 2 paths for Firefox:
  - OS X
    - Per-user: `~/Library/Application Support/Mozilla/NativeMessagingHosts/passff.json`
    - System-wide: `/Library/Application Support/Mozilla/NativeMessagingHosts/passff.json`

I guess you have a second path to check, while I do believe there should be nothing there. 
Do a search of `passff.json` if you feel like doing it (`find / -type f -name 'passff.json''` on GNU)

> I know pass works just fine as I use it all the time from the command line.

OK.

Your error message may be `[11:13:19] show -> gpg: decryption failed: No secret key (2)`
 I triggered this error by not entering my passphrase when I'm supposed to enter it in pinentry.

I suspect a problem with pin-entry. I do think your gpg-agent works since your passff would *sometimes* work.
 
1. Try passff. (It should not work: error 2)
2.  Decrypt a file with pass / gpg2, so as to enter your passphrase. *Theory: gpg-agent stores your passphrase for a while*
3. Try passff. *Theory: it will work since gpg-agent will gracefully give the pw for you*

You can create a new issue.

**Comment by tuxor1337** [comment]
Anything new about this?

**Comment by CCheCastaldo** [comment]
tuxor1337, see closed issue #325. That solved it for me.

**Comment by tuxor1337** [comment]
Okay, and how about you, @mziegler8888 ?

**Comment by kaskavalci** [comment]
I followed the steps in https://github.com/passff/passff/issues/324#issuecomment-380265297 and reinstalled from master. Using FF 61.0.1 (64-bit) and restarted browser after re-installing too.

For my case, I see the following log:
```
[PassFF] 0 matches for https://github.com/passff/passff/issues/324 util.js:36:9
[PassFF] Tab init done 7 https://github.com/passff/passff/issues/324 util.js:36:9
[PassFF] Message Pass.loadItems received in background util.js:36:9
[PassFF] Message Menu.getLastState received in background util.js:36:9 
```
However extensions shows the error with incorrect (earlier) timestamp. Restarting the browser updated this timestamp but behavior is the same.
```Connection to the host app failed or returned an unexpected result!
[08:52:03] ls -> (-1) no error message
```

**Comment by 5bentz** [comment]
You can install official versions for now, they are up-to-date with master :1st_place_medal: 

The steps are now included in PassFF-host documentation, with more details:
* [Troubleshooting](https://github.com/passff/passff-host#troubleshooting)
* [Advanced Troubleshooting](https://github.com/passff/passff-host#advanced-troubleshooting)

In the console, at 8:52, you should have a log saying "Error executing pass script". If you enable Debugging Mode (visit `about:debugging` webpage), and then reload the extension, you should be able to see it. (see Advanced Troubleshooting)

Especially make sure that:
* you **really** uninstall all installations of PassFF-host (see Troubleshooting)
* you install passff.json **correctly**: verify its variable `path` is the _absolute_ path to passff.py (see Troubleshooting)
* you can execute passff.py and it outputs relevant information (see Advanced troubleshooting)

**Copy-paste the commands and their results here.**

Good luck :+1:

**Comment by kaskavalci** [comment]
Thanks for the response @5bentz. Currently none of the following attempts succeed. Please note that I was able to use the extension for once when I installed it for the first time. 

* I removed passff extension and pass-host completely, from user and system level. I only use Firefox.
* I reinstalled passff extension and installed passff-host from 1.0.1 release with
  * `curl -sSL https://github.com/passff/passff-host/releases/download/1.0.1/install_host_app.sh | bash -s -- firefox`
* I checked `path` field in the `passff.json` and it is correct and absolute.
* Enabled console logging, reloaded plugin and from debugging console:

```
Webconsole context has changed
[PassFF] Error executing pass script Error: "undefined"
executePassmoz-extension://88333948-0e5a-7c47-ae7c-ec0aee73555b/modules/pass.js:228:16 util.js:36:9
[PassFF] loadItems failed! util.js:36:9
[PassFF] Init auth module util.js:36:9
[PassFF] Awaiting tab init... 1 about:addons util.js:36:9
[PassFF] Tab init done 1 about:addons util.js:36:9
[PassFF] Awaiting tab init... 1 about:addons util.js:36:9
[PassFF] Tab init done 1 about:addons util.js:36:9
[PassFF] Awaiting tab init... 5 https://github.com/passff/passff-host util.js:36:9
[PassFF] 0 matches for https://github.com/passff/passff-host
util.js:36:9
Error: ID already exists: remove-open-in-this-container ext-menus.js
Error: ID already exists: separator ext-menus.js
Error: ID already exists: hide-container ext-menus.js
Error: ID already exists: move-to-new-window-container ext-menus.js
[PassFF] Message Pass.loadItems received in background util.js:36:9
[PassFF] Message Page.goToAutoFillPending received in background util.js:36:9
[PassFF] Message Preferences.getKeyboardShortcut received in background util.js:36:9
[PassFF] Tab init done 5 https://github.com/passff/passff-host util.js:36:9
[PassFF] Message Pass.loadItems received in background util.js:36:9
[PassFF] Message Menu.getLastState received in background util.js:36:9
[PassFF] Create menu list 
Array []
util.js:36:9
[PassFF] Create children menu list 
Array []
 true util.js:36:9
[PassFF] Awaiting tab init... 5 https://github.com/passff/passff-host util.js:36:9
[PassFF] Tab init done 5 https://github.com/passff/passff-host
```
* Trying to run `passff.py`outputs:
```
$ echo -e "\x02\x00\x00\x00[]" | ./passff.py | tail -c +4; echo
Traceback (most recent call last):
  File "./passff.py", line 93, in <module>
    "stdout": proc.stdout.decode(CHARSET),
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 399: invalid continuation byte
```

**Comment by 5bentz** [comment]
That's odd.
FIrst, I see you downloaded the outdated version 1.0.1 of passff-host. I fixed the doc so as to link to the newest 1.0.2 file.
However, you have a charset error. Your shell seems not sending UTF-8 chars to `passff.py`...

You may find out your locale & charset with the command `locale`, modify passff's CHARSET variable accordingly.

**Comment by kaskavalci** [comment]
I removed 1.0.1 and installed 1.0.2 now. For a brief moment extension showed me a different screen than the error page but debugging was not enabled so I don't have any logs. I see the same error message now.

My locale is set to `en_US.UTF-8`
.profile:
```
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8
```
locale
```
$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

**Comment by 5bentz** [comment]
I would think the CHARSET must be set to the system's encoding...

However, you are setting these in your shell:
```
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8
```

What is your locale without this configuration? Move .profile to .profile.bak, run a new shell and check locale :)

Use this information to edit `passff.py` and change `CHARSET` to `ISO-8859-1` or `ISO-8859-15` or w/e.

My hypothesis is that your system encoding is different. Some password files have names with special characters that aren't ASCII. `passff.py` calls `pass` with your system environment, that happily sends back a byte stream in an unknown charset...Does that make sense?

I will assume `ISO-8859-1` or `ISO-8859-15` since these are encoding proposed for NL locales. (Oh I forgot to mention I assume you live in the Netherlands :D)
If I understand correctly, byte `0xc5` is :
- in `UTF-8`: a byte that starts a two-byte char: see char 197 [here](https://en.wikipedia.org/wiki/UTF-8)
- in `ISO-8859-1`: the character `Å`  ( `A` with a `°` diacritic)
Thus, a password filename should contain this character.

EDIT: Oh I see that `Å` is used in the Walloon language! :P I assume you are a Wallon-speaking in the Netherlands. Let me a few days to figure out where you live thanks to `UnicodeDecodeError`s! :joy:

**Comment by kaskavalci** [comment]
OK I think I found out the issue now, thanks for the tips. I used `lastpass2pass.rb` to migrate my lastpass data to pass. Some of the sites there have some Turkish characters. Although system locale is set to en_US.utf-8 in terminal and system language altogether, when decoding a Turkish character like "ş" gives that error. If I use pass to insert such character, pass decodes it to utf-8 automatically.

```
pass insert test-ş
 create mode 100644 "test-\305\237.gpg"
```

but surprisingly this doesn't work with passff either.

```
Traceback (most recent call last):
  File "./passff.py", line 93, in <module>
    "stdout": proc.stdout.decode(CHARSET),
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 1012: invalid continuation byte
```

Currently I found the workaround with feeding `ignore` on decode errors. 

```python
sendMessage(encodeMessage({
        "exitCode": proc.returncode,
        "stdout": proc.stdout.decode(CHARSET, "ignore"),
        "stderr": proc.stderr.decode(CHARSET, "ignore"),
        "version": VERSION
    }))
```

Sorry I kinda hijacked this issue with the charset problem.

**Comment by tuxor1337** [comment]
@kaskavalci and @5bentz: Please continue this discussion in https://github.com/passff/passff-host/issues/25

@mziegler8888 Anything new about your original issue?

**Comment by tuxor1337** [comment]
Closing due to inactivity.
