### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by akissz** [passff/passff#446]
I tried to get this passff to function but I am not able to get the host app setup with the given instructions on both ths passff page and the host app page. I got all the pass steps to function. But the install sh script does nothing on my test system (I don't know why.). So I copied the host app manually to Firefox profile directory from the host app github, the passff.py and passff.json files. This did nothing. I get the generic error in the passff plugin that the host app needs to be installed. I'm using FreeBSD 12. Can someone write better instructions for FreeBSD or is passff not compatible with FreeBSD?

Also I don't understand the whole directory native-messaging-hosts. Because no other FF plugin puts directories in the Firefox directory in that manner. The instructions are written not clear on the host app install page. Seems the whole directory setup in the program should be programmed better, in my view.

I tried a test command but I don't know if I am doing it correct:

```
echo -e "\x02\x00\x00\x00[]" | /home/angel/.mozilla/native-messaging-hosts/passff.py | tail -c +4 ; echo
```

And I get this:
```
Traceback (most recent call last):
  File "/home/angel/.mozilla/native-messaging-hosts/passff.py", line 57, in <module>
    receivedMessage = getMessage()
  File "/home/angel/.mozilla/native-messaging-hosts/passff.py", line 38, in getMessage
    return json.loads(message)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Smile.

**Comment by tuxor1337** [comment]
Yes, BSD support seems to be difficult. There are also problems with MacOS and OpenBSD: https://github.com/passff/passff/issues/217

**Comment by akissz** [comment]
Well I hope support is added. The PassFF seems like one of the best password programs/plugins that I have seen lately.

**Comment by akissz** [comment]
Yes the Firefox version I tested with is just the recent version 80. And the FreeBSD shell default for new users: sh.

**Comment by akissz** [comment]
Looking more today I read the line
For the install script (except Windows)
    curl
    sed

And I read SED and I did not know this program. So I study it a little. I think default FreeBSD had sed. But I installed gsed . No idea what the difference is but then now when I run the install script it functions and installs all the files.

And now the plugin functions. I don't know why... Functions good today. Did "gsed" help? Or maybe I did something randomly different than yesterday.

But now I have more comments. 
It is a lovely plugin.
Only complaint now is the add user function window needs some css styles; it looks ugly by default and does not match the other parts of the plugin.

Hopefully as time goes by with Firefox changes then updates are made for major compatibility issues, if there are any in the future.
Great plugin.

**Comment by tuxor1337** [comment]
Thanks for your feedback!

Could you please elaborate on this:
> Only complaint now is the add user function window needs some css styles; it looks ugly by default and does not match the other parts of the plugin.
I don't understand what you mean by "add user function window". What is a "user function"?

**Comment by akissz** [comment]
After clicking on the P when you click the + symbol this pops up the add window. At least in Firefox in FreeBSD. And the fonts do not match the rest of the plugin. And the window is in a odd placement in center (why not corner of browser like the rest of the plugin). I mean compared to the main plugin window in the corner of the browser when you click on the P icon in Firefox. I only assume the fonts don't match in other operating systems too. The design of the main plugin part is excellent.

**Comment by tuxor1337** [comment]
Closing due to inactivity.

Since this seems to be related to the host application, please open a new issue in the [passff-host repository](https://github.com/passff/passff-host/issues) in case you would like to continue the discussion.
